# Nome da aplica��o
spring.application.name=api

# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=postdba

# Atualiza o esquema do banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

# Exibir no terminal o SQL sendo executado
spring.jpa.show-sql=true

# Informa para não formatar o SQL
spring.jpa.properties.hibernate.format_sql=false